site_name: DerekDekker 文档

# 主题
theme:
  features:
    - navigation.tabs  # 导航
    - search.suggest  # 搜索建议
    - search.highlight  # 搜索高亮
    - search.share  # 搜索分享

  name: material
#  custom_dir: overrides
  language: zh  # 语言

  # 主题颜色
  palette:
    scheme: slate  # 背景 default | slate
    primary: red  # 主体颜色
    accent: red  # 链接 按钮等颜色

# 社交链接
extra:
  social:
    - icon: fontawesome/brands/twitter  # 推特
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/facebook  # 脸书
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/github  # GitHub
      link: https://twitter.com/squidfunk

# GitHub 仓库
repo_url: https://github.com/DerekDekker/Docu

# 导航
nav:
  - Python:
    - 基础: Python/基础.md
    - 数据类型: Python/数据类型.md
    - pip: Python/pip.md
    - os: Python/os.md
    - beautifulsoup4: Python/beautifulsoup4.md


